[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="cmpage" type="com.coremedia.blueprint.common.contentbeans.Page" --]
[#import "/lib/coremedia.com/cae.ftl" as cm]
[#import "/lib/coremedia.com/blueprint.ftl" as bp]